### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by MorisR** [shoogkabiya/fruits#2]
this variable is not being referenced/used:

https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/server.js#L5
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/public/script.js#L3
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/public/script.js#L5

**Comment by shoogkabiya** [comment]
this variable is not being referenced/used:
i deleted it .

**Comment by shoogkabiya** [comment]
const datalisto = document.querySelector(".datalisto"); 
i edit it  to the-datalist.

**Comment by shoogkabiya** [comment]
i use it when i change the API_URL to local or i can change to online .
const local = `http://localhost:3000`;
const online = `https://fruitsdata.herokuapp.com`;
const API_URL = local;


function getData(searched) {
  fetch(`${API_URL}/getdata?name=${searched}`)
    .then((res) => res.json())
    .then((res) => {
      renderList(res);
      globalData = res;
    })
    .catch((err) => {
      console.log(err);
    });
}

**Comment by MorisR** [comment]
hmmmm ok, i see what you mean 👍
