### ISSUE TITLE
missing index.js

### ISSUE THREAD

**Issue by MorisR** [shoogkabiya/fruits#3]
the project should include a clear starting point ( a file that tells you where the project starts ) 
traditionally an "index.js" file is included in the root directory of the project (and sometimes even in directories like src/server) to indicate the starting point of the project/directory/etc..

the "main" field in the  ```package.json``` file should also reference that starting point file
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/package.json#L5

**Comment by shoogkabiya** [comment]
i did it 
  <script src="/public/elements.js"></script>
    <script src="/public/index.js"></script>
    <script src="/public/testjscript.js"></script>
"name": "fruits",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",

**Comment by MorisR** [comment]
yeah but what i mean is when someone starts working on the project with you, they need a clear and defined starting point.
in your case it's server.js 

you can either rename it to index.js or update the package json
