### ISSUE TITLE
api route could potentially fail 

### ISSUE THREAD

**Issue by MorisR** [shoogkabiya/fruits#4]
in case the api call fails - you should still return a response
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/handlers/fruitData.js#L16-L18

**Comment by shoogkabiya** [comment]
i did it 
api(url)
    .then((res) => {
      response.writeHead(200, { "content-type": "application/json" });
      response.end(JSON.stringify(res.body.data[0].images.original.url));
    })
    .catch((err) => {
      console.log(err);
      // response.writeHead(404, { "content-type": "test/plain" });
      response.end(err.message);
      // response.end("not found");
    });

**Comment by shoogkabiya** [comment]
i did it  
api(url)
    .then((res) => {
      response.writeHead(200, { "content-type": "application/json" });
      response.end(JSON.stringify(res.body.data[0].images.original.url));
    })
    .catch((err) => {
      console.log(err);
     
      response.end(err.message);
   
    });

**Comment by MorisR** [comment]
👍 👍 👍 👍
