### ISSUE TITLE
remove console logs and commented out code

### ISSUE THREAD

**Issue by MorisR** [shoogkabiya/fruits#5]
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/handlers/fruitData.js#L1
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/handlers/fruitData.js#L8
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/handlers/fruitData.js#L10
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/public/script.js#L10-L11
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/public/script.js#L25
https://github.com/shoogkabiya/fruits/blob/main/backend/public/script.js#L49

**Comment by shoogkabiya** [comment]
i did it   thank you for your notes
