### ISSUE TITLE
change these to actual if statements

### ISSUE THREAD

**Issue by MorisR** [shoogkabiya/fruits#8]
by changing the "&&" and the "inline if" to actual if statements, the code would become more readable 
 
https://github.com/shoogkabiya/fruits/blob/b32dfe6e2386c493bcc94db285ad4cdcda220096/backend/public/script.js#L44-L45

**Comment by shoogkabiya** [comment]
i did it ....
search.addEventListener("input", (e) => {
  const searched = e.target.value;

  if (searched.length >= 0) {
    getData(searched);
  }

 
  if (search.value === "") {
    innerHTML = "";
  } else {
    return null;
  }
});

**Comment by MorisR** [comment]
there's no need for the 
```
else {
return null;
}
```

you'll get the same result with it or without it,
either way, good job!

**Comment by shoogkabiya** [comment]
thanks
